# project info
site_name: 乐聊官网
site_description: This site is CHaT++ Website
site_author: samzong.lu
repo_url: https://github.com/SAMZONG/oversea-docs
repo_name: samzong/oversea-docs
edit_uri: ./edit/main/docs

theme:
  name: material
  language: zh

  icon:
    repo: fontawesome/brands/github

  palette:
    scheme: indigo

  font:
    text: Roboto

  features:
    - navigation.tabs
    - navigation.tabs.sticky

    - search.suggest
    - search.highlight
    - search.share

    - header.autohide

plugins:
  - search
  - tags
  - mermaid2

extra_javascript:
  - https://unpkg.com/mermaid/dist/mermaid.min.js

markdown_extensions:
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
      title: On this page
      toc_depth: 3
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite

nav:
  - 首页: index.md
  - 乐聊客服工作台: chatplus_introduction.md
  # - 乐聊客服机器人: chatplus_aibot.md
  - 更新日志: chatplus_release_log.md
  - 帮助手册: chatplus_manual.md
  - 关于我们:
      - 我们的服务: our_service.md
      - 我们的客户: our_customers.md
      - 合作伙伴: our_parnters.md
  - 客户端下载:
      - PC端:
          - Windows: chatplus_win.md
          - Mac: chatplus_mac.md
      - 移动端: chatplus_moblie.md
  - 立即注册使用: register.md
  - 请求功能演示: request_demo.md
